# Learning Python

Some basics

In [5]:
#Camel Case
myVariableName = "John"

#Pascal Case
MyVariableName = "John"

#Snake Case
my_variable_name = "John"

## W 3 Schools Lessons

#### Multi-assignment in python

In [3]:
x, y, z, = 1, 2, 3
print(x, y, z)

1 2 3


#### Unpack a Collection

If you have a collection of values in a list, tuple etc. Python allows you to extract the values into variables. This is called unpacking.

In [ ]:
fruits = ["apple", "banana", "cherry"]
x, y, z = fruits
print(x)
print(y)
print(z)

Built-in Data Types
In programming, data type is an important concept.

Variables can store data of different types, and different types can do different things.

Python has the following data types built-in by default, in these categories:

1. Text Type:	str
2. Numeric Types:	int, float, complex
3. Sequence Types:	list, tuple, range
4. Mapping Type:	dict
5. Set Types:	set, frozenset
6. Boolean Type:	bool
7. Binary Types:	bytes, bytearray, memoryview
8. None Type:	NoneType

In [ ]:
x = 1    # int
y = 2.8  # float
z = 1j   # complex

#### Float and scientific notation for writing floats

Float can also be scientific numbers with an "e" or "E" to indicate the power of 10.

In [21]:
x = 35e3
y = 12E4
z = -87.7e100

print(x, "\n", y, "\n", z)

35000.0 
 120000.0 
 -8.77e+101


In [10]:
# Get the datatype
try:
    x1 = {name:"Faizan", "age":34}
except:
    print("Did not define the dict correctly.", "\n")

x1 = {"name":"Faizan", "age":34}
print(x1)

try:
    for obj in list:
        try:
            print(type(obj))
        except:
            print("The obj is not assinged anything.|")
except:
    print("Learning with errors.", "\n")

Did not define the dict correctly. 

{'name': 'Faizan', 'age': 34}
Learning with errors. 



#### The correct way of creating a dictionary obj

Use this `x = dict(name = "Faizan", age = 34)`

Instead of `x = {"name" = "Faizan", "age" = 34}`

There is a lot less typing invovled in the first method. Also, not making the key a string feels more natural to me, though for automation it is of course better to have the key entered as a string. Also, using the equal sign `=` instead of the colon `:` for linking the key with the value also feels more natural.


In [11]:
x = dict(name="John", age=36)
print(x, type(x))

{'name': 'John', 'age': 36} <class 'dict'>


In [3]:
x = memoryview(bytes(5))
x

### Random Numbers in Python

Python does not have a random() function to make a random number, but Python has a built-in module called random that can be used to make random numbers:
Import the random module, and display a random number between 1 and 9:

In [22]:
import random

print(random.randrange(1, 10))

1


## Strings, String Methods, and manipulation in python

String manipulation is amazing in python. It is next level in my humble opinion.

In [23]:
txt = "The best things in life are free!"
print("free" in txt)

True


In [24]:
txt = "The best things in life are free!"
if "free" in txt:
  print("Yes, 'free' is present.")

Yes, 'free' is present.


In [ ]:
txt = "The best things in life are free!"
print("expensive" not in txt)

In [ ]:
txt = "The best things in life are free!"
if "expensive" not in txt:
  print("No, 'expensive' is NOT present.")

In [ ]:
a = "Hello, World!"
print(a.upper())

In [ ]:
a = "Hello, World!"
print(a.lower())

In [ ]:
a = " Hello, World! "
print(a.strip()) # returns "Hello, World!"

In [ ]:
a = "Hello, World!"
print(a.replace("H", "J"))

In [ ]:
a = "Hello, World!"
print(a.split(",")) # returns ['Hello', ' World!']

In [25]:
age = 36
txt = "My name is John, I am " + age
print(txt)

TypeError: can only concatenate str (not "int") to str

We can combine strings and numbers by using the format() method!

The format() method takes the passed arguments, formats them, and places them in the string where the placeholders {} are:

In [ ]:
age = 36
txt = "My name is John, and I am {}"
print(txt.format(age))

The format() method takes unlimited number of arguments, and are placed into the respective placeholders:

In [26]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want {} pieces of item {} for {} dollars."
print(myorder.format(quantity, itemno, price))

I want 3 pieces of item 567 for 49.95 dollars.


You can use index numbers {0} to be sure the arguments are placed in the correct placeholders:

In [27]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {2} dollars for {0} pieces of item {1}."
print(myorder.format(quantity, itemno, price))

I want to pay 49.95 dollars for 3 pieces of item 567.


To insert characters that are illegal in a string, use an escape character.

An escape character is a backslash \ followed by the character you want to insert.

An example of an illegal character is a double quote inside a string that is surrounded by double quotes:

In [28]:
txt = "We are the so-called "Vikings" from the north."

SyntaxError: invalid syntax (7934146.py, line 1)

In [30]:
txt = "We are the so-called \"Vikings\" from the north."
print(txt)

We are the so-called "Vikings" from the north.


Illegal characters

\'	Single Quote	
\\	Backslash	
\n	New Line	
\r	Carriage Return	
\t	Tab	
\b	Backspace	
\f	Form Feed	
\ooo	Octal value	
\xhh	Hex value

Method	Description
* capitalize()	Converts the first character to upper case
* casefold()	Converts string into lower case
* center()	Returns a centered string
* count()	Returns the number of times a specified value occurs in a string
* encode()	Returns an encoded version of the string
* endswith()	Returns true if the string ends with the specified value
* expandtabs()	Sets the tab size of the string
* find()	Searches the string for a specified value and returns the position of where it was found
* format()	Formats specified values in a string
* format_map()	Formats specified values in a string
* index()	Searches the string for a specified value and returns the position of where it was found
* isalnum()	Returns True if all characters in the string are alphanumeric
* isalpha()	Returns True if all characters in the string are in the alphabet
* isdecimal()	Returns True if all characters in the string are decimals
* isdigit()	Returns True if all characters in the string are digits
* isidentifier()	Returns True if the string is an identifier
* islower()	Returns True if all characters in the string are lower case
* isnumeric()	Returns True if all characters in the string are numeric
* isprintable()	Returns True if all characters in the string are printable
* isspace()	Returns True if all characters in the string are whitespaces
* istitle()	Returns True if the string follows the rules of a title
* isupper()	Returns True if all characters in the string are upper case
* join()	Joins the elements of an iterable to the end of the string
* ljust()	Returns a left justified version of the string
* lower()	Converts a string into lower case
* lstrip()	Returns a left trim version of the string
* maketrans()	Returns a translation table to be used in translations
* partition()	Returns a tuple where the string is parted into three parts
* replace()	Returns a string where a specified value is replaced with a specified value
* rfind()	Searches the string for a specified value and returns the last position of where it was found
* rindex()	Searches the string for a specified value and returns the last position of where it was found
* rjust()	Returns a right justified version of the string
* rpartition()	Returns a tuple where the string is parted into three parts
* rsplit()	Splits the string at the specified separator, and returns a list
* rstrip()	Returns a right trim version of the string
* split()	Splits the string at the specified separator, and returns a list
* splitlines()	Splits the string at line breaks and returns a list
* startswith()	Returns true if the string starts with the specified value
* strip()	Returns a trimmed version of the string
* swapcase()	Swaps cases, lower case becomes upper case and vice versa
* title()	Converts the first character of each word to upper case
* translate()	Returns a translated string
* upper()	Converts a string into upper case
* zfill()	Fills the string with a specified number of 0 values at the beginning

## Boolians

In [1]:
print(bool("Hello"))
print(bool(15))

True
True


In [9]:
x, y, z, z1, z2, z3 = "Hello", 15, -1, "", 0, None
print(x, y, z, z1, z2, z3)
print( bool(x), bool(y), bool(z), bool(z1), bool(z2), bool(z3) )



Hello 15 -1  0 None
True True True False False False


In fact, there are not many values that evaluate to False, except empty values, such as (), [], {}, "", the number 0, and the value None. And of course the value False evaluates to False.

One more value, or object in this case, evaluates to False, and that is if you have an object that is made from a class with a __len__ function that returns 0 or False:

In [11]:
class myclass():
  def __len__(self):
    return 0

myobj = myclass()
print(bool(myobj))

False


## Functions Can also return Boolans
You can create functions that returns a Boolean Value:

Also, You can execute code based on the Boolean answer of a function:  !!!!

In [12]:
def myFunction() :
  return True

if myFunction():
  print("YES!")
else:
  print("NO!")

YES!


Python also has many built-in functions that return a boolean value, like the isinstance() function, which can be used to determine if an object is of a certain data type:

This is useful for automation where the type and the obj can be passed into the function isinstance():

In [13]:
x = 200
print(isinstance(x, int))

True


## Python divides the operators in the following groups:

* Arithmetic operators
* Assignment operators
* Comparison operators
* Logical operators
* Identity operators
* Membership operators
* Bitwise operators

%	         Modulus	     x % y This is the remainder operator the percent sign %


In [14]:
4%2

0

In [15]:
5%2

1

In [16]:
15%2

1

//	Floor division	x // y

In [20]:
4//2, 3//2, 5//2, 15//2

(2, 1, 2, 7)

In [23]:
fruits = ["apple", "banana"]
if "apple" in fruits:
    print("Yes, apple is a fruit!")

Yes, apple is a fruit!


## Lists Allow Duplicates
Since lists are indexed, lists can have items with the same value:

In [24]:
["apple", "banana", "cherry", "apple", "cherry"]

['apple', 'banana', 'cherry', 'apple', 'cherry']

A list can contain different data types:

In [25]:
["abc", 34, True, 40, "male"]

['abc', 34, True, 40, 'male']

## Python Collections (Arrays) Summary

There are four collection data types in the Python programming language:

- **List** is a collection which is ordered and changeable. Allows duplicate members.
- **Tuple** is a collection which is ordered and unchangeable. Allows duplicate members.
- **Set** is a collection which is unordered, unchangeable**, and unindexed. No duplicate members.
- **Dictionary** is a collection which is ordered*** and changeable. No duplicate members.

** Set items are unchangeable, but you can remove and/or add items whenever you like.

*** As of Python version 3.7, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered.

In [27]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:5])

['cherry', 'orange', 'kiwi']


This example returns the items from "orange" (-4) to, but NOT including "mango" (-1):

In [28]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[-4:-1])

['orange', 'kiwi', 'melon']


## Append Items

In [34]:
# We can append
thislist = ["apple", "banana", "cherry"]
thislist.append("orange")
print(thislist)

['apple', 'banana', 'cherry', 'orange']


## Insert Items

To insert a new list item, without replacing any of the existing values, we can use the insert() method.

The insert() method inserts an item at the specified index:

In [35]:
# Insert "watermelon" as the third item: 
thislist = ["apple", "banana", "cherry"]
thislist.insert(2, "watermelon")
print(thislist)

['apple', 'banana', 'watermelon', 'cherry']


## Extend List

To append elements from another list to the current list, use the extend() method.

Add the elements of tropical to thislist:

In [36]:
thislist = ["apple", "banana", "cherry"]
tropical = ["mango", "pineapple", "papaya"]
thislist.extend(tropical)
print(thislist)

['apple', 'banana', 'cherry', 'mango', 'pineapple', 'papaya']


The extend() method does not have to append lists, you can add any iterable object (tuples, sets, dictionaries etc.).

Add elements of a tuple to a list:

In [37]:
thislist = ["apple", "banana", "cherry"]
thistuple = ("kiwi", "orange")
thislist.extend(thistuple)
print(thislist)

['apple', 'banana', 'cherry', 'kiwi', 'orange']


Now try adding elements from a dictionary to the list.

## Remove Specified Item by specifying the actual object

The str.remove() method removes the specified item.

This list method modifies the actual list!!

In [43]:
thislist = ["apple", "banana", "cherry"]
thislist.remove("banana")
print(thislist)

['apple', 'cherry']


## Remove Specified Index

The str.pop() method removes the specified index.

If you do not specify the index, the pop() method removes the last item.

This list method modifies the actual list!!!!!

In [44]:
thislist = ["apple", "banana", "cherry"]
print(thislist)
thislist.pop(1)
print(thislist)
thislist.pop()
print(thislist)

['apple', 'banana', 'cherry']
['apple', 'cherry']
['apple']


### The del keyword

The del keyword also removes the specified index:

`del thislist[0]`

The del keyword can also delete the list completely.

`del thislist`

## Clear the List

The clear() method empties the list.

The list still remains, but it has no content.

In [45]:
thislist = ["apple", "banana", "cherry"]
thislist.clear()
print(thislist)

[]


## I. Lesson 1

The `.dtypes` dataframe method for dataframes from the Pandas library is different from the builtin python function `type()` 

In [1]:
import pandas as pd

In [4]:
df = pd.DataFrame()

In [5]:
df
df.dtypes

Series([], dtype: object)

## II. Chuck Severance Python for Everyone Assignments.

### As the user for his total hours and rate per hour thenb calculate their pay.

In [2]:
hrs = input("Enter hours:")
rate_per_hr = input("Enter rate per hour:")
print("Pay:", float(hrs) * float(rate_per_hr))
# use 35 hrs and 2.75 for rate_per_hr. Answer: 96.25

Enter hours: 35
Enter rate per hour: 2.75


Pay: 96.25


In [3]:
chr(1)

'\x01'

3.1 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay the hourly rate for the hours up to 40 and 1.5 times the hourly rate for all hours worked above 40 hours. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input - assume the user types numbers properly.


In [35]:
hrs = input("Enter Hours:")
rate_per_hour = input("Enter Hours:")
rate_per_hour = float(rate_per_hour)
h = float(hrs)

if h <= 40:
    print(h*rate_per_hour)
else:
    print(40*rate_per_hour + (h-40)*rate_per_hour*1.5)

Enter Hours: 45
Enter Hours: 10.5


498.75


3.3 Write a program to prompt for a score between 0.0 and 1.0. If the score is out of range, print an error. If the score is between 0.0 and 1.0, print a grade using the following table:
Score Grade
>= 0.9 A
>= 0.8 B
>= 0.7 C
>= 0.6 D
< 0.6 F
If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.


In [38]:
# This does not work correctly.

score = input("Enter Score: ")

try:
    fs = float(score)
    if fs > 1 | fs < 0 :
        print("Error, you are out of bounds.")
        quite()
except:
    score = input("You did not enter a number please enter a number:")
    
if fs >= .9:
    print("A")
elif fs >= .8:
    print('B')
elif fs >= .7:
    print('C')
elif fs >= .6:
    print('D')
else:
    print('F')

    


Enter Score:  .1
You did not enter a number please enter a number: 0


F


In [1]:
score = input("Enter Score: ")
fs = float(score)
#try:
#    fs = float(score)
#except:
    #score = input("You did not enter a number please enter a number:")    

# This does not work properly because the try except block should be in a while loop so that the score is fedback
# to the fs=float(score)

if fs > 1 or fs < 0 :
    print("Error, you are out of bounds.")
    quit()
else: 
    if fs >= .9:
        print("A")
    elif fs >= .8:
        print('B')
    elif fs >= .7:
        print('C')
    elif fs >= .6:
        print('D')
    else:
        print('F')


Enter Score:  10


Error, you are out of bounds.


In [2]:
score = input("Enter Score: ")
fs = float(score)

if fs > 1 or fs < 0 :
    print("Error, you are out of bounds.")
    quit()
else: 
    if fs >= .9:
        print("A")
    elif fs >= .8:
        print('B')
    elif fs >= .7:
        print('C')
    elif fs >= .6:
        print('D')
    else:
        print('F')

Enter Score:  .85


B


4.6 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. Do not name your variable sum or use the sum() function.

In [ ]:
def computepay(h, r):
    return 42.37

hrs = input("Enter Hours:")
p = computepay(45, 10.5)
print("Pay", p)

In [34]:
def computepay():
    hrs = input("Enter Hours:")
    payRate = input("Enter you pay rate:")
    
    h = float(hrs)
    p = float(payRate)
    
    if h > 40:
        pay = 40 * p + (h - 40) * p * 1.5
    else:
        pay = p * h
        
    return pay

#hrs = input("Enter Hours:")
p = computepay()
print("Pay", p)

Enter Hours: 45
Enter you pay rate: 10.5


Pay 498.75


In [2]:
def computepay():
    hrs = input("Enter Hours:")
    
    
    try:
        h = float(hrs)
    except:
        print("Error! You need to enter the hours as numbers - e.g. 45")
        quit()
        
    payRate = input("Enter you pay rate:")    
    try:
        p = float(payRate)
    except:
        print("Error! You need to enter your pay rate in numbers, e.g. 10.50")
        quit()
    
    if h > 40:
        pay = 40 * p + (h - 40) * p * 1.5
    else:
        pay = p * h
        
    return pay



In [3]:
#hrs = input("Enter Hours:")
p = computepay()
print("Pay", p)

Enter Hours: 45
Enter you pay rate: 10.5


Pay 498.75


In [4]:
p = computepay()
print("Pay", p)

Enter Hours: ten


Error! You need to enter the hours as numbers - e.g. 45


Enter you pay rate: 10


UnboundLocalError: local variable 'h' referenced before assignment

### Find the largest number in a list

In [48]:
numbers = [23, 232, 12, 43, 44, -1, -3]

largestNum = numbers[0]
for num in numbers:
    if num > largestNum:
        largestNum = num
print(largestNum)

# Making the above into a function

def find_largNum(list_of_num) :
    
    largestNum = list_of_num[0]
    
    for num in list_of_num :
        if num > largestNum :
            largestNum = num
    
    return(largestNum)

find_largNum(numbers)
find_largNum([5, -1, 324, 1e10, -1e20])

232


10000000000.0

5.2 Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. Enter 7, 2, bob, 10, and 4 and match the output below.

In [5]:
largest = None
smallest = None

while True:
    
    num = input("Enter a number: ")
    if num == "done":
        break
        
    #print(num)
    
    try:
        num = int(num)
    except:
        print("Invalid input")
        continue
    
    if largest is None:
        largest = num
    if largest < num:
        largest = num
    if smallest is None:
        smallest = num
    if smallest > num:
        smallest = num
        

print("Maximum is", largest)
print("Minimum is", smallest)

Enter a number:  7
Enter a number:  2
Enter a number:  bob


Invalid input


Enter a number:  10
Enter a number:  4
Enter a number:  done


Maximum is 10
Minimum is 2


In [ ]:
largest = None
smallest = None
while True:
    num = input("Enter a number: ")

    if num == "done":
        break
    print(num)
              
    try:
        num
    except: 

print("Maximum", largest)

## LeetCode Questions

You are given a string s formed by digits and '#'. We want to map s to English lowercase characters as follows:

Characters ('a' to 'i') are represented by ('1' to '9') respectively.
Characters ('j' to 'z') are represented by ('10#' to '26#') respectively.
Return the string formed after mapping.

The test cases are generated so that a unique mapping will always exist.

 

Example 1:

Input: s = "10#11#12"
Output: "jkab"
Explanation: "j" -> "10#" , "k" -> "11#" , "a" -> "1" , "b" -> "2".
Example 2:

Input: s = "1326#"
Output: "acz"
 

Constraints:

1 <= s.length <= 1000
s consists of digits and the '#' letter.
s will be a valid string such that mapping is always possible.


In [7]:
class Solution:
    def freqAlphabets(self, s: str) -> str:
        apl = "abcdefghijklmnopqrsvwtxyz"

In [29]:
apl = "abcdefghijklmnopqrsvwtxyz"
len(apl)
apl.split()
apl_spl = [x for x in apl]

the_string = ""
for alph in apl_spl:
    the_string += alph
the_string

'abcdefghijklmnopqrsvwtxyz'

In [33]:
alphs = 'qwertyuiopasdfghjklzxcvbnm'
alphs = sorted(alphs)
print(len(alphs))

the_string = ""
for alph in alphs:
    the_string += alph
the_string

26


'abcdefghijklmnopqrstuvwxyz'

In [4]:
print("hello world")

hello world


Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

```
Example 1:

Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].

Example 2:

Input: nums = [3,2,4], target = 6
Output: [1,2]

Example 3:

Input: nums = [3,3], target = 6
Output: [0,1]
```

In [ ]:
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        
        nums < target

In [158]:

nums_original, target = [10, 22, 2,7,11,15],  9
nums = nums_original
print(nums)
#print(nums.sort())
print(nums)
#nums < target

[10, 22, 2, 7, 11, 15]
[10, 22, 2, 7, 11, 15]


In [87]:
nums.append(target)

In [89]:
print(nums)
nums.sort()
print(nums)
idxTarget = nums.index(target)
print("idxTarget:", idxTarget)
print(nums.index(target))

candidates = nums[:idxTarget]
print(nums[:idxTarget])
highest_candidate = candidates[-1]
candidate = target - highest_candidate
print(candidate)

if candidate in nums_original:
    print([nums.index(candidate), nums.index(highest_candidate)])
    

[2, 7, 9, 10, 11, 15, 22]
[2, 7, 9, 10, 11, 15, 22]
idxTarget: 2
2
[2, 7]
2
[0, 1]


In [159]:
def twoSum(nums, target, prt=False) :
    
    nums_original = nums.copy()
    
    print(nums) if prt else ""
    
    nums.append(target)
    
    print(nums) if prt else ""
    
    nums.sort()
    
    print(nums) if prt else ""
    
    idxTarget = nums.index(target)
    
    print("idxTarget:", idxTarget)  if prt else ""
    print(nums.index(target)) if prt else ""

    candidates = nums[:idxTarget]
    
    print(nums[:idxTarget]) if prt else ""
    
    highest_candidate = candidates[-1]
    candidate = target - highest_candidate
    
    print(candidate) if prt else ""

    if candidate in nums_original:
        
        
        idx_hightest = nums_original.index(highest_candidate) 
        
        try:
            nums_original.index(candidate,  idx_hightest, -1)
        except:
            nums_original.index(candidate, 0, idx_hightest)
        
        print("nums_original", nums_original) if prt else ""
        idxs = [nums_original.index(candidate), nums_original.index(highest_candidate)]
    
        print(idxs)  if prt else ""
        
        return(idxs)
    

In [160]:
ans1 = twoSum(nums, target)
print(ans1)
print("\n")
twoSum(nums, target, True)
print(twoSum([3,3], 6))

[2, 3]


[2, 7, 9, 10, 11, 15, 22]
[2, 7, 9, 10, 11, 15, 22, 9]
[2, 7, 9, 9, 10, 11, 15, 22]
idxTarget: 2
2
[2, 7]
2
nums_original [2, 7, 9, 10, 11, 15, 22]
[0, 1]
[0, 0]


In [161]:
twoSum([3,2,4], 6, True)

[3, 2, 4]
[3, 2, 4, 6]
[2, 3, 4, 6]
idxTarget: 3
3
[2, 3, 4]
2
nums_original [3, 2, 4]
[1, 2]


[1, 2]

In [162]:
twoSum([3,3], 6)

[0, 0]

In [65]:
import numpy as np

numss = np.array(nums)
print(numss)
type(numss)

mask = numss < target
print(mask)



target - numss[mask].max()

#numss[mask].idmax()





[ 2  7 10 11 15 22]
[ True  True False False False False]


2

In [148]:
[3,3].index(3)

0

In [156]:
[1, 2, 1, 3,3].index(3, -1,-1)

ValueError: 3 is not in list

# Amazon Coding Interview Questions

### Question 1.

Find the missing number in the array

You are given an array of positive numbers from 1 to n, such that all numbers from 1 to n are present except one number x. You have to find x. The input array is not sorted. Look at the below array and give it a try before checking the solution.

3
7
1
2
8
4
5
n = 8 missing number = 6

In [14]:
seq = [3, 7, 1, 2, 8, 4, 5]

max_num = max(seq)
print(max_num)

seq_full = list(range(max_num + 1))
seq_full_sum = sum(seq_full)
print(seq_full_sum)

seq_sum = sum(seq)
print(seq_sum)

missing_number = seq_full_sum - seq_sum
print(missing_number)



8
36
30
6


In [15]:
# Creating sequences but not as range() object but as lists. Note have to add + 1 to the end if want to get it, which we usually need to get.
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### Question 2.

Determine if the sum of two integers is equal to the given value.

Given an array of integers and a value, determine if there are any two integers in the array whose sum is equal to the given value. Return true if the sum exists and return false if it does not. Consider this array and the target sums:

5
7
1
2
8
4
3
Target Sum
10
7+3=10, 2+8=10
Target Sum
19
No 2 values sum up to 19

### Question 3. 

Merge two sorted linked lists

Given two sorted linked lists, merge them so that the resulting linked list is also sorted. Consider two sorted linked lists and the merged list below them as an example.


In [17]:
list_1 = [4, 8, 15, 19]
list_2 = [7, 9, 10, 16]


sorted_list = []

if list_1[0] >= list_2[0] :
    sorted_list.append(list_2[0])
else :
    sorted_list.append(list_1[0])

for el_1 in list_1:
    for el_2 in list_2:
        
        print(sorted_list)
        

sorted_list = []

for i in range(  max(len(list_1), len(list_2))  ):
    min(list_1[i], list_2[i])
        

[4]
[4]
[4]
[4]
[4]
[4]
[4]
[4]
[4]
[4]
[4]
[4]
[4]
[4]
[4]
[4]


In [19]:
list(range(len(list_1)))

[0, 1, 2, 3]